// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"database/sql"
	"errors"
	"myapp/internal/dao/internal"
	"myapp/internal/model/entity"
)

// tUserDao is the data access object for the table t_user.
// You can define custom methods on it to extend its functionality as needed.
type tUserDao struct {
	*internal.TUserDao
}

var (
	// TUser is a globally accessible object for table t_user operations.
	TUser = tUserDao{internal.NewTUserDao()}
)

// Add your custom methods and functionality below.

func (d *tUserDao) GetUserByName(name string) (*entity.TUser, error) {
	user := &entity.TUser{}
	strSql := "SELECT * FROM t_user WHERE name = ?"
	err := db.QueryRow(strSql, name).Scan(&user.Id, &user.Name, &user.Password, &user.Email, &user.LastLoginAt, &user.Sex, &user.Age)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.New("用户不存在")
		}
		return nil, err
	}

	return user, nil
}
